version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: mi-node-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mi-mysql-app
      - MYSQL_USER=miuser
      - MYSQL_PASS=mipass
      - MYSQL_DB=mi_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "29999:8080"
    container_name: mi-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=miuser
      - MYSQL_PASSWORD=mipass 
      - MYSQL_DATABASE=mi_db
    container_name: mi-mysql-app
networks:
  frontend:
  backend: